---
# synchronization of repositories

# if you skip synchronization and
# you added kickstart repos to your product and content views
# satellite doesnt register the kickstart repos as synchronized content (obviously)
# new definitions like hostgroups then fail with bad content definitions
# avoid setting skip_sync_all or skip_publish_all in your variable file
# call it with an extravar instead

- name: "Get the unique list of rhisam products"
  when: repository_sets_rhisam is defined
  ansible.builtin.set_fact:
    products_to_sync: "{{ repository_sets_rhisam | map(attribute='product') | list | unique }}"

- name: "List the products to be synchronized"
  ansible.builtin.debug:
    var: products_to_sync

- name: "Sync the rhisam products with the CDN"
  ansible.builtin.include_tasks: "sync_product.yml"
  loop: "{{ products_to_sync }}"
  loop_control:
    loop_var: product_to_sync

- name: "Get the unique list of user products"
  when: repository_sets_user is defined
  ansible.builtin.set_fact:
    products_to_sync: "{{ repository_sets_user | map(attribute='product') | list | unique }}"

- name: "List the products to be synchronized"
  ansible.builtin.debug:
    var: products_to_sync

- name: "Sync the user products"
  ansible.builtin.include_tasks: "sync_product.yml"
  loop: "{{ products_to_sync }}"
  loop_control:
    loop_var: product_to_sync

- name: "Get the unique list of custom products"
  when: custom_products is defined
  ansible.builtin.set_fact:
    products_to_sync: "{{ custom_products | map(attribute='name') | list | unique }}"

- name: "List the products to be synchronized"
  ansible.builtin.debug:
    var: products_to_sync

- name: "Sync the custom products"
  ansible.builtin.include_tasks: "sync_product.yml"
  loop: "{{ products_to_sync }}"
  loop_control:
    loop_var: product_to_sync