---
# Activation keys that we use in the RH-ISAM

activation_keys_rhisam:
  - name: "SOE_RHEL8"
    state: "present"
    description: "Activate a RHEL 8 system"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "satellite-client-6-for-rhel-8-x86_64-rpms"
        override: "enabled"
    content_view: "SOE_RHEL8"
    lifecycle_environment: "Development"
    unlimited_hosts: true

# aks_user:
