---

# Use skip_publish_all when debugging configuration that occurs
# after content view creation and publication to help speed up the run
# if you turn it on here remember that things like new kickstarts won't
# published which may break things like hostgroups that reference new kickstarts...

skip_publish_all: false

# This contains all the definitions for Content Views and Composite Content Views
# It defines the filters and filter rules for the content views as well

errata_end_date: "{{ ansible_date_time.date }}"

# These content views are needed to build the environment or run a workflow.
# Do not remove them. You will want them anyway.
# You can always copy one, paste it into user and modify the repos and filters to test new ones
# Where a CV is only used in conjunction with another CV in a composite, it is only published to Library

cvs_rhisam:

# RHEL8 for lots of things
  - name: "SOE_RHEL8"
    desc: "Red Hat Enterprise Linux 8 Standard Operating Environment Content"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - Supplementary RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
    filters:
      - name: "Include_All_Packages_No_Errata"
        type: "rpm"
        inclusion: true
        description: "Include all rpms with no errata for all repositories"
        original_packages: true
        repositories: "[]"
      - name: "Include_All_Streams_No_Errata"
        type: "modulemd"
        inclusion: true
        description: "Include all module streams with no errata for all repositories"
        original_module_streams: true
        repositories: "[]"
      - name: "Include_Errata_By_Date"
        type: "erratum"
        inclusion: true
        description: "Include all errata updated as of {{ errata_end_date }}"
        repositories: "[]"
        rules:
          - name: "errata-by-date-{{ errata_end_date }}"
            end_date: "{{ errata_end_date }}"
            date_type: "updated"
            types:
              - "enhancement"
              - "bugfix"
              - "security"
      - name: "Exclude_FireFox"
        type: "rpm"
        inclusion: false
        description: "Do not provide Firefox to servers"
        repositories: "[]"
        rules:
          - name: "firefox*"
            basearch: "x86_64"
    date_filter_name: "Include_Errata_By_Date"
    environments:
      - "Library"
      - "Development"
      - "Qualification"
      - "Production"

# If you added the user products, you want these user CV configs
# cvs_user:

# These are the composite content views necessary for the RH-ISAM
# ccvs_rhisam:

# ccvs_user:
