---
# Domains registered in Satellite
# A given domain is serviced by only one capsule
# A given domain may exist in multiple orgs and locations

domains_rhisam:
# The domain of the Satellite Server
  - name: "{{ satellite_domain }}"
    description: "root domain for the installation"
    dns_capsule: "{{ satellite_fqdn }}"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

# domains_user:
# uncomment and add your domains here if you need more
