---
# Satellite Hostgroup configurations

hostgroups_rhisam:
  - name: "RHEL8base"
    description: "RHEL 8 SOE base hostgroup"
    activation_keys: "SOE_RHEL8"
    architecture: "x86_64"
    content_source: "{{ ansible_fqdn }}"
    content_view: "SOE_RHEL8"
    domain: "{{ satellite_domain }}"
    lifecycle_environment: "Development"
    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    locations: "{{ satellite_location }}"
    organization: "{{ satellite_organization }}"
    openscap_capsule: "{{ satellite_fqdn }}"
    operatingsystem: "RHEL 8.10"
    ptable: "RHEL_Server_CIS1"
    pxe_loader: "Grub2 UEFI"
    subnet: "labsubnet"

  - name: "RHEL8_CIS2_RAID"
    parent: "RHEL8base"
    description: "RHEL 8 SOE for CIS Server 2 compliance template"
    ptable: "RHEL_Server_Compliance_Encrypted_RAID"
    organization: "{{ satellite_organization }}"
    parameters:
      - name: "binding_json"
        type: "string"
        value: "{"t":3,"pins":{"tpm2":{"hash":"sha256","key":"ecc"},"tang":[{"url":"http://10.160.28.31:8080"},{"url":"http://10.160.28.32:8080"},{"url":"http://10.160.28.33:8080"},{"url":"http://10.160.28.34:8080"},{"url":"http://10.160.28.35:8080"}]}}"
      - name: "binding_type"
        type: "string"
        value: "sss"
      - name: "enc_target_drives"
        type: "array"
        value: "["/dev/disk/by-id/md-name-root"]"
      - name: "use_NBDE"
        type: "boolean"
        value: "true"

  - name: "RHEL8_CIS2_RAID_meta"
    parent: "RHEL8base"
    description: "RHEL 8 SOE for CIS Server 2 compliance template"
    ptable: "RHEL_Server_Compliance_Encrypted_RAID"
    organization: "{{ satellite_organization }}"
    parameters:
      - name: "binding_json"
        type: "string"
        value: "{"t":3,"pins":{"tpm2":{"hash":"sha256","key":"ecc"},"tang":[{"url":"http://10.160.28.31:8080"},{"url":"http://10.160.28.32:8080"},{"url":"http://10.160.28.33:8080"},{"url":"http://10.160.28.34:8080"},{"url":"http://10.160.28.35:8080"}]}}"
      - name: "binding_type"
        type: "string"
        value: "sss"
      - name: "enc_target_drives"
        type: "array"
        value: "["/dev/disk/by-id/md-name-root","/dev/nvme0n1p1","/dev/nvme1n1p1"]"
      - name: "use_NBDE"
        type: "boolean"
        value: "true"