---

# ansible roles
# This is necessary as we are calling using the URI today
# redhat.satellite does not support importing ansible roles at this time
# The name is "smart_proxies.id-smart_proxies.name"
# The Satellite that you are installing is always 1
satellite_api_proxy_id_string: "1-{{ satellite_fqdn }}"

ansible_roles_import_list:
  - "ansible-role-rhel9-e8"
  - "ansible-role-rhel9-ism"
  - "ansible-role-rhel9-cui"
  - "ansible-role-rhel9-pci-dss"
  - "ansible-role-rhel9-ospp"
  - "ansible-role-rhel9-hipaa"
  - "ansible-role-rhel9-cis"
  - "ansible-role-rhel9-anssi_bp28_minimal"
  - "ansible-role-rhel9-anssi_bp28_intermediary"
  - "ansible-role-rhel9-anssi_bp28_high"
  - "ansible-role-rhel9-stig"
  - "ansible-role-rhel8-cui"
  - "ansible-role-rhel8-rht-ccp"
  - "ansible-role-rhel8-pci-dss"
  - "ansible-role-rhel8-ospp"
  - "ansible-role-rhel8-hipaa"
  - "ansible-role-rhel8-cjis"
  - "ansible-role-rhel8-cis"
  - "ansible-role-anssi_bp28_minimal"
  - "ansible-role-anssi_bp28_intermediary"
  - "ansible-role-rhel8-anssi_bp28_high"
  - "ansible-role-anssi_bp28_enhanced"
  - "ansible-role-rhel8-stig"
  - "ansible-role-rhel7-cui"
  - "ansible-role-rhel7-pci-dss"
  - "ansible-role-rhel7-ospp"
  - "ansible-role-rhel7-cjis"
  - "ansible-role-rhel7-cis"
  - "ansible-role-rhel7-stig"
  - "ansible-role-anssi_nt28_minimal"
  - "ansible-role-anssi_bp28_intermediary"
  - "ansible-role-anssi_bp28_high"
  - "ansible-role-anssi_bp28_enhanced"
  - "theforeman.foreman_scap_client"
  - "RedHatInsights.insights-client"
