---
# All of the templates that we need in a Satellite that aren't already installed.
# Add your template files to the files directory of the Role
# OR add them in this hostvars folder and adjust the path

provisioning_templates_rhisam:
# snippets
  - name: "soe_create_users_selinux"
    type: "snippet"
    locked: false
    description: "Create default users based on satellite owner"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_create_users_selinux.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_disable_non_sat_repos"
    type: "snippet"
    locked: false
    description: "Disable configured host repositories not provided by Satellite"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_disable_non_sat_repos.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_ensure_python"
    type: "snippet"
    locked: false
    description: "Ensure that the proper OS python version is installed (RHEL8)"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_ensure_python.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_ifcfg_generic_interface"
    type: "snippet"
    locked: false
    description: "Modified to support defined network zone"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_kickstart_ifcfg_generic_interface.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_install_cockpit"
    type: "snippet"
    locked: false
    description: "Ensure that the cockpit web UI is installed and enabled"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_install_cockpit.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "SOE Kickstart Default custom packages"
    type: "snippet"
    locked: false
    description: "Adding a list of standard SOE packages to be installed on every SOE image"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_kickstart_default_custom_packages.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_kickstart_ifcfg_bond_interface"
    type: "snippet"
    locked: false
    description: "Modified to support defined network zone"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_kickstart_ifcfg_bond_interface.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_kickstart_ifcfg_bonded_interface"
    type: "snippet"
    locked: false
    description: "Modified to support defined network zone"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_kickstart_ifcfg_bonded_interface.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_kickstart_networking_setup"
    type: "snippet"
    locked: false
    description: "Modified to support defined network zone"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_kickstart_networking_setup.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "soe_use_NBDE"
    type: "snippet"
    locked: false
    description: "Enables Network Bound Disk Encryption for host. REQUIRES encrypted type ptable. REQUIRES active tang servers."
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_snippet_soe_use_NBDE.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

# provisioning
  - name: "SOE Kickstart Default Finish"
    type: "provision"
    locked: false
    description: "The default finish kickstart for image based provisioning of SOE systems"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_soe_kickstart_default_finish.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "SOE Kickstart Default PXELinux"
    type: "provision"
    locked: false
    description: "The default kickstart for PXE provisioning SOE systems"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_soe_kickstart_default_pxe_linux.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

  - name: "SOE Kickstart Default"
    type: "provision"
    locked: false
    description: "The default kickstart for network based provisioning SOE systems"
    audit_comment: "created by rhis-builder-satellite"
    path: "prov_template_soe_kickstart_default.j2"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"

# provisioning_templates_user:
# There are none
