---
# The rhisam does not provide a manifest.
# All manifests manifests must be provided by the user
# The code can generate a manifest for the user based on the providing the info below
# This defines manifests that we will create

redhat_manifests:
  - name: "{{ ansible_fqdn }}"
    account: "{{ cdn_account_number_vault }}"
    cdn_username: "{{ cdn_username_vault }}"
    cdn_password: "{{ cdn_password_vault }}"
    content_access_mode: "org_environment"  # SCA mode
    organization: "Default Organization"
    path: "/root/bootstrap_manifest.zip"
    portal_url: "https://subscription.rhsm.redhat.com"
    state: present
    subs: "{{ manifest_subs_vault }}"
    validate_certs: true
#   repository_url:  # specify a url for alternate content source

# we want to eventually support searching by contract number + SKU

# example of subs dict
# parmstrong_ca_subs_vault:
#   - name: "Base"
#     pool_id: "2c946de78e8076d6018e85b1e0b375e8"                                                  # notsecret
#     pool_state: present
#     qty: 1000
#   - name: "SatCapsule"
#     pool_id: "2c94f6188e80762a018e85b358943df1"                                                   # notsecret
#     pool_state: present
#     qty: 1
#   - name: "NonRHEL"
#     pool_id: "2c94f6188e80762a018e85b2bb4b3dec"                                                   # notsecret
#     pool_state: present
#     qty: 100
