---
# discovery rules.
# ensure target hostgroup exists

discovery_rules_rhisam:
  - name: "3nic_host"
    enabled: false
    state: present
    organizations: "{{ satellite_organization }}"
    locations: "{{ satellite_location }}"
    search: 'disk_count = 2 and memory > 32000 and facts.interfaces ~ "*,*,*,*"'
    priority: 20
    hostgroup: "RHEL8base/RHEL8_CIS2_RAID"
