---
# This file holds the main satellite level variables.

satellite_fqdn: "{{ groups['sat_primary'][0] }}"
satellite_admin_username: "{{ satellite_admin_username_vault }}"
satellite_admin_password: "{{ satellite_admin_password_vault }}"
satellite_initial_location: "Default Location"
satellite_initial_organization: "Default Organization"
satellite_location: "{{ satellite_initial_location }}"
satellite_organization: "{{ satellite_initial_organization }}"
satellite_domain: "ironmountain.com"
satellite_url: "https://{{ satellite_fqdn }}"
satellite_validate_certs: false
satellite_admin_email: "{{ satellite_admin_username }}@{{ satellite_domain }}"

async_timeout: 14400
async_delay: 15
cv_publish_timeout: "{{ async_timeout }}"
cv_publish_retry_interval: "{{ async_delay }}"
