# general_settings
# Tell the linter to ignore long lines
# yamllint disable rule:line-length

# to reset the value to the default do not provide a value parameter.

settings_general:
  - description: "The default administrator email address"
    settings_type: "string"
    default: "root@parmstrong.ca"
    updated_at: null
    id: "administrator"
    name: "administrator"
    full_name: "Administrator email address"
    value: "root@parmstrong.ca"
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "URL where your Foreman instance is reachable (see also Provisioning unattended_url)"
    settings_type: "string"
    default: "https://sat6.parmstrong.ca"
    updated_at: null
    id: "foreman_url"
    name: "foreman_url"
    full_name: "Foreman URL"
    value: "https://sat6.parmstrong.ca"
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Number of records shown per page in Foreman"
    settings_type: "integer"
    default: 20
    updated_at: null
    id: "entries_per_page"
    name: "entries_per_page"
    full_name: "Entries per page"
    value: 20
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Should the `foreman-rake db:seed` be executed on the next run of the installer modules?"
    settings_type: "boolean"
    default: true
    updated_at: "2022-11-18 03:50:50 UTC"
    id: "db_pending_seed"
    name: "db_pending_seed"
    full_name: "DB pending seed"
    value: false
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Open and read timeout for HTTP requests from Foreman to Smart Proxy (in seconds)"
    settings_type: "integer"
    default: 60
    updated_at: null
    id: "proxy_request_timeout"
    name: "proxy_request_timeout"
    full_name: "Smart Proxy request timeout"
    value: 60
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Text to be shown in the login-page footer. Keyword $VERSION is replaced by current version."
    settings_type: "string"
    default: "Version $VERSION"
    updated_at: null
    id: "login_text"
    name: "login_text"
    full_name: "Login page footer text"
    value: "Version $VERSION"
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Set a proxy for all outgoing HTTP(S) connections from Foreman. System-wide proxies must be configured at the operating system level."
    settings_type: null
    default: null
    updated_at: null
    id: "http_proxy"
    name: "http_proxy"
    full_name: "HTTP(S) proxy"
    value: null
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Set hostnames to which requests are not to be proxied. Requests to the local host are excluded by default."
    settings_type: "array"
    default: []
    updated_at: null
    id: "http_proxy_except_list"
    name: "http_proxy_except_list"
    full_name: "HTTP(S) proxy except hosts"
    value: []
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Whether or not to show a menu to access experimental lab features (requires reload of page)"
    settings_type: "boolean"
    default: false
    updated_at: null
    id: "lab_features"
    name: "lab_features"
    full_name: "Show Experimental Labs"
    value: false
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Display names of hosts as FQDNs. If disabled, only display names of hosts as hostnames."
    settings_type: "boolean"
    default: true
    updated_at: null
    id: "display_fqdn_for_hosts"
    name: "display_fqdn_for_hosts"
    full_name: "Display names of hosts as FQDNs"
    value: true
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Duration in minutes after servers are classed as out of sync. This setting is overridden by specific settings from config management tools (e.g. puppet_inteval ansible_interval)."
    settings_type: "integer"
    default: 30
    updated_at: null
    id: "outofsync_interval"
    name: "outofsync_interval"
    full_name: "Out of sync interval"
    value: 30
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Foreman instance ID uniquely identifies this Foreman instance."
    settings_type: null
    default: null
    updated_at: "2022-11-18 03:50:04 UTC"
    id: "instance_id"
    name: "instance_id"
    full_name: "Foreman UUID"
    value: "e922ec86-392e-42fa-8e5d-628a2cd600f9"
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Language to use for new users"
    settings_type: null
    default: null
    updated_at: null
    id: "default_locale"
    name: "default_locale"
    full_name: "Default language"
    value: null
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false

  - description: "Timezone to use for new users"
    settings_type: null
    default: null
    updated_at: null
    id: "default_timezone"
    name: "default_timezone"
    full_name: "Default timezone"
    value: null
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false

  - description: "The instance title is shown on the top navigation bar (requires a page reload)."
    settings_type: null
    default: null
    updated_at: null
    id: "instance_title"
    name: "instance_title"
    full_name: "Instance title"
    value: null
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Duration in days to preserve audits for. Leave empty to disable the audits cleanup."
    settings_type: null
    default: null
    updated_at: null
    id: "audits_period"
    name: "audits_period"
    full_name: "Saved audits interval"
    value: null
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null

  - description: "Foreman will load the new UI for host details"
    settings_type: "boolean"
    default: true
    updated_at: null
    id: "host_details_ui"
    name: "host_details_ui"
    full_name: "New host details UI"
    value: true
    category: "general"
    category_name: "General"
    readonly: false
    config_file: null
    encrypted: false
    select_values: null
