---

# Maps our product into our sync plans
# NOTE - the file is named the other way around so you see it in the list and don't forget about it!

product_plan_rhisam:
  - name: "Red Hat Enterprise Linux Server for x86_64"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Enterprise Linux for x86_64"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Satellite Capsule"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

# If you added the user repos, make sure they get sync'd too.
# product_plan_user:
