---
# virtwho logins for satellite, capsule and hypervisors and their configurations

satellite_virtwho_username: "{{ satellite_virtwho_username_vault }}"
satellite_virtwho_password: "{{ satellite_virtwho_password_vault }}"

vcenter_virtwho_username: "{{ vcenter_virtwho_username_vault }}"
vcenter_virtwho_password: "{{ vcenter_virtwho_password_vault }}"

virtwho_configs_rhisam:
  - foreman_virt_who_configure_config:
      name: "VMware"
      hypervisor_type: "esx"
      hypervisor_server: "vcenter,parmstrong.ca"
      hypervisor_username: "{{ vcenter_virtwho_username }}"
      hypervisor_password: "{{ vcenter_virtwho_password }}"
      hypervisor_id: "hostname"
      interval: "120"
      filtering_mode: 0
      satellite_url: "{{ satellite_fqdn }}"
      organization_name: "{{ satellite_organization }}"
      organization_id: 0    # this id will get looked up and assigned base on the name
